### ISSUE TITLE
Java UnsatisfiedLinkError: libpjsua.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by BaybaraEvgeny** [pjsip/pjproject#2695]
I want to use pjsip in my java application. 
I follow all the steps from the instruction:

./configure --enable-shared
make dep & make
sudo make install

then include path in LD_LIBRARY_PATH
then I invoke ```make``` and ```make install``` manually from ```pjsip-apps/src/swig``` directory

All build goes without errors.

But when I try to import ```System.loadLibrary("pjsua2");```  I get this error:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: 
/home/baybara/IdeaProjects/pjproject-2.11/pjsip-apps/src/swig/java/output/libpjsua2.so: libpjsua.so.2: cannot open shared object file: No such file or directory
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2659)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.base/java.lang.System.loadLibrary(System.java:1873)
	at test.<clinit>(test.java:5)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.execute(Main.java:391)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.run(Main.java:179)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.main(Main.java:119)
```

I use ubuntu 20.10, java 11 and pjsip 2.11

**Comment by BaybaraEvgeny** [comment]
It seems that I fixed that... Just had to install python-dev and properly include path in LD_LIBRARY_PATH.

**Comment by BMatthai** [comment]
What path do you include in LD_LIBRARY_PATH ?

**Comment by Apteryks** [comment]
I'm guessing it had to do with commit 742f7dc25 Fix installation of libpjsua2 shared libraries (#2670).
