### ISSUE TITLE
[feature] adding python3 variant of old python2 bindings: almost works but gives SystemError

### ISSUE THREAD

**Issue by warpme** [pjsip/pjproject#2895]
### Describe the bug

In my project (MiniMyth2) I wrote simple python2 based SIP daemon.
It uses "old" python2 bindings (non-swig; from pjsip-apps/src/python) & works very well.

Recently I switched to python3 and i want to have working my simple python2 based SIP daemon under python3.
As using new, swig based python bindings require almost full rewrite of my daemon - i decided to port "old" python2 bindings to python3. (pls see attached patches). My work is based on https://github.com/mgwilliams/python3-pjsip

Attached patches giving me working my SIP daemon on python3 (it registers, i can conduct SIP calls, etc) - but i have issue:

on SIP INVITE i'm receiving 
```
Exception ignored in thread started by: <function _worker_thread_main at 0x7ff63d944c10>
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pjsua.py", line 2949, in _worker_thread_main
    _lib.handle_events(1)
  File "/usr/lib/python3.8/site-packages/pjsua.py", line 2259, in handle_events
    return _pjsua.handle_events(timeout)
SystemError: <built-in function handle_events> returned a result with an error set
```
I'm asking here for help regarding my porting python2 to python3 changes: probably i missed something or i'm doing something wrong...

Pls see attached changes in: _pjsua.c _pjsua.h pjsua.py and also log from SIP call.

PS: I think my work with porting old style python bindings to python3 might be nice addition for all PJSIP users having written SIP apps for python2 and wanting move to python3 with minimal effort...
  
[pjsua.py.patch.zip](https://github.com/pjsip/pjproject/files/7576273/pjsua.py.patch.zip)
[_pjsua.h.patch.zip](https://github.com/pjsip/pjproject/files/7576274/_pjsua.h.patch.zip)
[_pjsua.c.patch.zip](https://github.com/pjsip/pjproject/files/7576275/_pjsua.c.patch.zip)
[run.log](https://github.com/pjsip/pjproject/files/7576276/run.log)

 

### Steps to reproduce

SIP INVITE is enough to trigger issue.

### PJSIP version

PJSIP2.11.1; python3.8.11

### Context

In my project (MiniMyth2) I wrote simple python2 based SIP daemon.
It uses "old" python2 bindings (non-swig; from pjsip-apps/src/python) & works very well.
Recently I switched to python3 and i want to have working my simple python2 based SIP daemon under python3.
As using new, swig based python bindings require almost full rewrite of my daemon - i want to keep my app minimally changed and port "old" python2 bindings to python3.

### Log, call stack, etc

```shell
13:23:22.831         os_core_unix.c !pjlib 2.11.1 for POSIX initialized
13:23:22.832         sip_endpoint.c  .Creating endpoint instance...
13:23:22.832                  pjlib  .select() I/O Queue created (0x1212b70)
13:23:22.832         sip_endpoint.c  .Module "mod-msg-print" registered
13:23:22.832        sip_transport.c  .Transport manager created.
13:23:22.832           pjsua_core.c  .PJSUA state changed: NULL --> CREATED
before paHostApiInitializers[0].
ALSA version (build): 1.2.5.1
ALSA version (runtime): 1.2.5.1
BuildDeviceList: Found device [0]: HDA Intel PCH: ALC269VC Analog (hw:0,0)
BuildDeviceList: Found device [1]: HDA Intel PCH: HDMI 0 (hw:0,3)
BuildDeviceList: Found device [2]: HDA Intel PCH: HDMI 1 (hw:0,7)
BuildDeviceList: Found device [3]: HDA Intel PCH: HDMI 2 (hw:0,8)
BuildDeviceList: Found device [4]: HDA Intel PCH: HDMI 3 (hw:0,9)
BuildDeviceList: Found device [5]: HDA Intel PCH: HDMI 4 (hw:0,10)
BuildDeviceList: Ignoring ALSA plugin device [hw] of type [hw]
BuildDeviceList: Ignoring ALSA plugin device [plughw] of type [plug]
BuildDeviceList: Ignoring ALSA plugin device [plug] of type [plug]
BuildDeviceList: Ignoring ALSA plugin device [shm] of type [shm]
BuildDeviceList: Ignoring ALSA plugin device [tee] of type [file]
BuildDeviceList: Ignoring ALSA plugin device [file] of type [file]
BuildDeviceList: Ignoring ALSA plugin device [null] of type [null]
BuildDeviceList: Ignoring ALSA plugin device [cards] of type [unknown]
BuildDeviceList: Found plugin [sysdefault] of type [unknown]
BuildDeviceList: Found plugin [front] of type [unknown]
BuildDeviceList: Found plugin [rear] of type [unknown]
BuildDeviceList: Found plugin [center_lfe] of type [unknown]
BuildDeviceList: Found plugin [side] of type [unknown]
BuildDeviceList: Found plugin [surround21] of type [unknown]
BuildDeviceList: Found plugin [surround40] of type [unknown]
BuildDeviceList: Found plugin [surround41] of type [unknown]
BuildDeviceList: Found plugin [surround50] of type [unknown]
BuildDeviceList: Found plugin [surround51] of type [unknown]
BuildDeviceList: Found plugin [surround71] of type [unknown]
BuildDeviceList: Found plugin [iec958] of type [unknown]
BuildDeviceList: Found plugin [spdif] of type [unknown]
BuildDeviceList: Found plugin [hdmi] of type [unknown]
BuildDeviceList: Found plugin [dmix] of type [unknown]
BuildDeviceList: Ignoring ALSA plugin device [dsnoop] of type [unknown]
BuildDeviceList: Found plugin [modem] of type [unknown]
BuildDeviceList: Found plugin [phoneline] of type [unknown]
BuildDeviceList: Found plugin [default] of type [plug]
BuildDeviceList: Filling device info for 24 devices
FillInDevInfo: Filling device info for: HDA Intel PCH: ALC269VC Analog (hw:0,0)
GropeDevice: collecting info ..
GropeDevice: collecting info ..
Default input device: HDA Intel PCH: ALC269VC Analog (hw:0,0)
Default output device: HDA Intel PCH: ALC269VC Analog (hw:0,0)
FillInDevInfo: Adding device HDA Intel PCH: ALC269VC Analog (hw:0,0): 0
FillInDevInfo: Filling device info for: HDA Intel PCH: HDMI 0 (hw:0,3)
GropeDevice: collecting info ..
FillInDevInfo: Adding device HDA Intel PCH: HDMI 0 (hw:0,3): 1
FillInDevInfo: Filling device info for: HDA Intel PCH: HDMI 1 (hw:0,7)
GropeDevice: collecting info ..
FillInDevInfo: Adding device HDA Intel PCH: HDMI 1 (hw:0,7): 2
FillInDevInfo: Filling device info for: HDA Intel PCH: HDMI 2 (hw:0,8)
GropeDevice: collecting info ..
FillInDevInfo: Adding device HDA Intel PCH: HDMI 2 (hw:0,8): 3
FillInDevInfo: Filling device info for: HDA Intel PCH: HDMI 3 (hw:0,9)
GropeDevice: collecting info ..
FillInDevInfo: Adding device HDA Intel PCH: HDMI 3 (hw:0,9): 4
FillInDevInfo: Filling device info for: HDA Intel PCH: HDMI 4 (hw:0,10)
GropeDevice: collecting info ..
FillInDevInfo: Adding device HDA Intel PCH: HDMI 4 (hw:0,10): 5
FillInDevInfo: Filling device info for: sysdefault
GropeDevice: collecting info ..
GropeDevice: Limiting number of plugin channels to 128
GropeDevice: collecting info ..
GropeDevice: Limiting number of plugin channels to 128
FillInDevInfo: Adding device sysdefault: 6
FillInDevInfo: Filling device info for: front
GropeDevice: collecting info ..
FillInDevInfo: Adding device front: 7
FillInDevInfo: Filling device info for: rear
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
OpenPcm: Opened device 'rear' ptr[(nil)] - result: [-2:No such file or directory]
FillInDevInfo: Skipped device: rear, all channels == 0
FillInDevInfo: Filling device info for: center_lfe
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
OpenPcm: Opened device 'center_lfe' ptr[(nil)] - result: [-2:No such file or directory]
FillInDevInfo: Skipped device: center_lfe, all channels == 0
FillInDevInfo: Filling device info for: side
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
OpenPcm: Opened device 'side' ptr[(nil)] - result: [-2:No such file or directory]
FillInDevInfo: Skipped device: side, all channels == 0
FillInDevInfo: Filling device info for: surround21
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
OpenPcm: Opened device 'surround21' ptr[(nil)] - result: [-22:Invalid argument]
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
OpenPcm: Opened device 'surround21' ptr[(nil)] - result: [-22:Invalid argument]
FillInDevInfo: Skipped device: surround21, all channels == 0
FillInDevInfo: Filling device info for: surround40
GropeDevice: collecting info ..
FillInDevInfo: Adding device surround40: 8
FillInDevInfo: Filling device info for: surround41
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
OpenPcm: Opened device 'surround41' ptr[(nil)] - result: [-22:Invalid argument]
FillInDevInfo: Skipped device: surround41, all channels == 0
FillInDevInfo: Filling device info for: surround50
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
OpenPcm: Opened device 'surround50' ptr[(nil)] - result: [-22:Invalid argument]
FillInDevInfo: Skipped device: surround50, all channels == 0
FillInDevInfo: Filling device info for: surround51
GropeDevice: collecting info ..
FillInDevInfo: Adding device surround51: 9
FillInDevInfo: Filling device info for: surround71
GropeDevice: collecting info ..
FillInDevInfo: Adding device surround71: 10
FillInDevInfo: Filling device info for: iec958
OpenPcm: Opened device 'iec958' ptr[(nil)] - result: [-2:No such file or directory]
FillInDevInfo: Skipped device: iec958, all channels == 0
FillInDevInfo: Filling device info for: spdif
OpenPcm: Opened device 'spdif' ptr[(nil)] - result: [-2:No such file or directory]
OpenPcm: Opened device 'spdif' ptr[(nil)] - result: [-2:No such file or directory]
FillInDevInfo: Skipped device: spdif, all channels == 0
FillInDevInfo: Filling device info for: hdmi
OpenPcm: Opened device 'hdmi' ptr[(nil)] - result: [-2:No such file or directory]
GropeDevice: collecting info ..
FillInDevInfo: Adding device hdmi: 11
FillInDevInfo: Filling device info for: modem
OpenPcm: Opened device 'modem' ptr[(nil)] - result: [-2:No such file or directory]
OpenPcm: Opened device 'modem' ptr[(nil)] - result: [-2:No such file or directory]
FillInDevInfo: Skipped device: modem, all channels == 0
FillInDevInfo: Filling device info for: phoneline
OpenPcm: Opened device 'phoneline' ptr[(nil)] - result: [-2:No such file or directory]
OpenPcm: Opened device 'phoneline' ptr[(nil)] - result: [-2:No such file or directory]
FillInDevInfo: Skipped device: phoneline, all channels == 0
FillInDevInfo: Filling device info for: dmix
GropeDevice: collecting info ..
FillInDevInfo: Adding device dmix: 12
FillInDevInfo: Filling device info for: default
OpenPcm: Opened device 'default' ptr[(nil)] - result: [-2:No such file or directory]
GropeDevice: collecting info ..
GropeDevice: Limiting number of plugin channels to 128
Default output device: default
FillInDevInfo: Adding device default: 13
BuildDeviceList: Building device list took 0.064629 seconds
after paHostApiInitializers[0].
b'13:23:22.900           pjsua_core.c  .pjsua version 2.11.1 for Linux-5.15.3/x86_64/glibc-2.34 initialized\n'
PaAlsaStreamComponent_Initialize: Host Chans C 2
AlsaOpen: Opening device hw:0,0
PaAlsaStreamComponent_InitialConfigure: device MMAP SND_PCM_ACCESS_MMAP_INTERLEAVED: YES
PaAlsaStreamComponent_InitialConfigure: device MMAP SND_PCM_ACCESS_MMAP_NONINTERLEAVED: NO
PaAlsaStreamComponent_InitialConfigure: device can MMAP: YES
PaAlsaStreamComponent_DetermineFramesPerBuffer: user-buffer (frames)           = 882
PaAlsaStreamComponent_DetermineFramesPerBuffer: user-buffer (sec)              = 0.020000
PaAlsaStreamComponent_DetermineFramesPerBuffer: suggested latency (sec)        = 0.100000
PaAlsaStreamComponent_DetermineFramesPerBuffer: suggested host buffer (frames) = 5292
PaAlsaStreamComponent_DetermineFramesPerBuffer: suggested host buffer (sec)    = 0.120000
PaAlsaStreamComponent_DetermineFramesPerBuffer: periods min = 2, max = 32, req = 4
PaAlsaStreamComponent_DetermineFramesPerBuffer: suggested host buffer period   = 1764
PaAlsaStreamComponent_DetermineFramesPerBuffer: device period minimum          = 32
PaAlsaStreamComponent_DetermineFramesPerBuffer: device period maximum          = 524288
PaAlsaStreamComponent_DetermineFramesPerBuffer: host buffer period             = 1764
PaAlsaStreamComponent_DetermineFramesPerBuffer: host buffer period latency     = 0.040000
PaAlsaStream_Configure: Capture period size: 1764, latency: 0.120000
OpenStream: Stream: framesPerBuffer = 882, maxFramesPerHostBuffer = 1764, latency i=0.120000, o=0.000000
PaAlsaStreamComponent_Initialize: Host Chans P 2
AlsaOpen: Opening device hw:0,3
PaAlsaStreamComponent_InitialConfigure: device MMAP SND_PCM_ACCESS_MMAP_INTERLEAVED: YES
PaAlsaStreamComponent_InitialConfigure: device MMAP SND_PCM_ACCESS_MMAP_NONINTERLEAVED: NO
PaAlsaStreamComponent_InitialConfigure: device can MMAP: YES
PaAlsaStreamComponent_DetermineFramesPerBuffer: user-buffer (frames)           = 882
PaAlsaStreamComponent_DetermineFramesPerBuffer: user-buffer (sec)              = 0.020000
PaAlsaStreamComponent_DetermineFramesPerBuffer: suggested latency (sec)        = 0.140000
PaAlsaStreamComponent_DetermineFramesPerBuffer: suggested host buffer (frames) = 7056
PaAlsaStreamComponent_DetermineFramesPerBuffer: suggested host buffer (sec)    = 0.160000
PaAlsaStreamComponent_DetermineFramesPerBuffer: periods min = 2, max = 32, req = 4
PaAlsaStreamComponent_DetermineFramesPerBuffer: suggested host buffer period   = 1764
PaAlsaStreamComponent_DetermineFramesPerBuffer: device period minimum          = 32
PaAlsaStreamComponent_DetermineFramesPerBuffer: device period maximum          = 16384
PaAlsaStreamComponent_DetermineFramesPerBuffer: host buffer period             = 1764
PaAlsaStreamComponent_DetermineFramesPerBuffer: host buffer period latency     = 0.040000
PaAlsaStream_Configure: Playback period size: 1764, latency: 0.160000
OpenStream: Stream: framesPerBuffer = 882, maxFramesPerHostBuffer = 1764, latency i=0.000000, o=0.160000
PaUnixThread_New: Waited for 0.00662684 seconds for stream to start
PaUnixThread_New: Waited for 0.000152111 seconds for stream to start
b'13:23:22.940            pjsua_acc.c !....<sip:konto-206@192.168.1.254>: registration success, status=200 (OK), will re-register in 300 seconds\n'
13:23:22.946 Registration complete, status=200(OK)
OnExit: Stopping ALSA handles
AlsaStop: Dropped frames
OnExit: Stoppage
CallbackThreadFunc: Thread 997393984 exiting
 OnExit: Stopping ALSA handles
AlsaStop: Dropped frames
OnExit: Stoppage
CallbackThreadFunc: Thread 1005786688 exiting
 Stopping callback
PaUnixThread_Terminate: Joining thread 1005786688
Stopping callback
PaUnixThread_Terminate: Joining thread 997393984
Exception ignored in thread started by: <function _worker_thread_main at 0x7ff63d944c10>
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pjsua.py", line 2949, in _worker_thread_main
    _lib.handle_events(1)
  File "/usr/lib/python3.8/site-packages/pjsua.py", line 2259, in handle_events
    return _pjsua.handle_events(timeout)
SystemError: <built-in function handle_events> returned a result with an error set
```

**Comment by sauwming** [comment]
Sorry for not being able to give an earlier response. Hopefully you have been able to resolve it by now.
