### ISSUE TITLE
PJSIP crashes on Assertion `ctx.last_error != PJ_SUCCESS' when dealing with a forked 200 Answering message

### ISSUE THREAD

**Issue by Kexin6** [pjsip/pjproject#3335]
### Describe the bug

This error occurs when PJSIP parses a forked 200 Answering request containing an invalid attribute. This causes PJSIP to crash on an assertion. Please see the log section below for more details.

### Steps to reproduce

1. Compile PJSIP binaries under pjproject directory: `./configure --disable-strip CFLAGS=-g && make dep && make clean && make`

2. Compile Baresip binary under baresip directory: `make -C deps/re install PREFIX=$PWD/bin && make -C deps/rem install PREFIX=$PWD/bin LIBRE_MK=$SIP_FUZZER_DIR/baresip/deps/re/mk/re.mk && make PREFIX=$PWD/bin LIBRE_MK=deps/re/mk/re.mk LIBRE_INC=bin/include/re/ LIBRE_SO=bin/lib/ LIBREM_PATH=bin/ install`

3. Launch SIP Simple UA service: `./pjproject/pjsip-apps/bin/samples/x86_64-unknown-linux-gnu/simpleua sip:user@127.0.0.1:5061`

4. Launch Baresip client: `./baresip -f docs/examples -n 127.0.0.1 -e \"/accept\"`

5. Baresip starts to communicate with simpleua (Please refer to the log section below for more details)

6. At some time, the assertion will occur when baresip sends the following **forked** INVITE message with an invalid attribute `jv`:

```
	INVITE SIP/2.0 200 Answering

	Via: SIP/2.0/UDP 172.17.0.2:5060;branch=z9hG4bKPjiNeUsXjdMuRBU2j.KGSI94O1i7pQoYqc;rport=5060;received=127.0.0.1

	From: <sip:simpleuac@172.17.0.2>;tag=PKcMBzp6yhIZQG-du1TsYkW1MPmX6L5V

	To: sip:user@127.0.0.1;tag=5326e903b0627b77

	Call-ID: 2mdIf8lexOTBIMg2pPgKOBdDB3SowCcf

	CSeq: 124 INVITE

	Server: baresip v0.6.2 (x86_64/linux)

	Contact: <sip:user-0x117e010@127.0.0.1:5061>

	Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,NOTIFY,SUBSCRIBE,INFO,MESSAGE,REFER

	Content-Type: application/sdp

	Content-Length: 320


	jv=0

	o=- 2171053277 1572505827 IN IP4 127.0.0.1

	s=-

	c=IN IP4 127.0.0.1

	t=0 0

	a=tool:baresip 0.6.2

	m=audio 47698 RTP/AVP 0 8 96

	a=rtpmap:0 PCMU/8000

	a=rtpmap:8 PCMA/8000

	a=rtpmap:96 telephone-event/8000

	a=fmtp:96 0-15

	a=sendrecv

	a=label:1

	a=rtcp-rsize

	a=ssrc:2304287767 cname:sip:user@127.0.0.1

	a=ptime:20
```

### PJSIP version

2.8

### Context

The error occurs when PJSIP parses the first line of the incoming SDP body, specifically when the scanner’s current pointer has a value of “j” where “jv” is an invalid SDP field. This results in the exception `SYNTAX_ERROR` being thrown and the `PJ_CATCH_ANY` block in _sdp.c_ being entered. In normal executions, `ctx.last_error` should be set to `PJMEDIA_SDP_EINSDP` instead of `PJ_SUCCESS`. The code should enter the default switch block and call the `parse_generic_line()` function in _sdp.c:1449_.

The root cause of the assertion is PJSIP’s failure to handle a **forked 200 message** properly. Our rudimentary analysis suggests that `ctx.last_error`’s value is flushed whenever PJSIP parses forked messages, resulting in this error occurring when receiving any malformed forked messages, including but not limited to 200 Answering. This issue may also affect the parsing and proper erroring of malformed 180 Ringing and 183 Session Progress messages.

Thank you for your time and attention. We’re happy to provide any information you need and help you come up with a patch. 

### Log, call stack, etc

```shell
************************************Full Log************************************

14:04:36.824         os_core_unix.c !pjlib 2.8 for POSIX initialized
14:04:36.824         sip_endpoint.c  Creating endpoint instance...
14:04:36.825                  pjlib  select() I/O Queue created (0x6280000031c0)
14:04:36.825         sip_endpoint.c  Module "mod-msg-print" registered
14:04:36.825        sip_transport.c  Transport manager created.
14:04:36.826      udp0x615000000080  SIP UDP transport started, published address is 172.17.0.2:5060
14:04:36.826         sip_endpoint.c  Module "mod-tsx-layer" registered
14:04:36.826         sip_endpoint.c  Module "mod-stateful-util" registered
14:04:36.826         sip_endpoint.c  Module "mod-ua" registered
14:04:36.826         sip_endpoint.c  Module "mod-invite" registered
14:04:36.826         sip_endpoint.c  Module "mod-100rel" registered
14:04:36.826         sip_endpoint.c  Module "mod-simpleua" registered
14:04:36.826         sip_endpoint.c  Module "mod-msg-log" registered
14:04:36.826                  pjlib  select() I/O Queue created (0x61f0000000a8)
14:04:36.827      dlg0x61d000000128  UAC dialog created
14:04:36.827      dlg0x61d000000128  Module mod-invite added as dialog usage, data=0x6190000019a8
14:04:36.827      dlg0x61d000000128  .Session count inc to 2 by mod-invite
14:04:36.827      dlg0x61d000000128  Module mod-100rel added as dialog usage, data=0x619000001cb0
14:04:36.827      dlg0x61d000000128  100rel module attached
14:04:36.827      inv0x61d000000128  UAC invite session created for dialog dlg0x61d000000128
14:04:36.827               endpoint  Request msg INVITE/cseq=125 (tdta0x62100001b9a8) created.
14:04:36.827      inv0x61d000000128  .Sending Request msg INVITE/cseq=125 (tdta0x62100001b9a8)
14:04:36.827      dlg0x61d000000128  ..Sending Request msg INVITE/cseq=125 (tdta0x62100001b9a8)
14:04:36.827      tsx0x61d000000b28  ...Transaction created for Request msg INVITE/cseq=124 (tdta0x62100001b9a8)
14:04:36.827      tsx0x61d000000b28  ..Sending Request msg INVITE/cseq=124 (tdta0x62100001b9a8) in state Null
14:04:36.827          sip_resolve.c  ...Target '127.0.0.1:5061' type=Unspecified resolved to '127.0.0.1:5061' type=UDP (UDP transport)
14:04:36.827             simpleua.c  ...TX 724 bytes Request msg INVITE/cseq=124 (tdta0x62100001b9a8) to UDP 127.0.0.1:5061:
INVITE sip:user@127.0.0.1:5061 SIP/2.0

Via: SIP/2.0/UDP 172.17.0.2:5060;rport;branch=z9hG4bKPjiNeUsXjdMuRBU2j.KGSI94O1i7pQoYqc

Max-Forwards: 70

From: <sip:simpleuac@172.17.0.2>;tag=PKcMBzp6yhIZQG-du1TsYkW1MPmX6L5V

To: sip:user@127.0.0.1

Contact: <sip:simpleuac@172.17.0.2:5060>

Call-ID: 2mdIf8lexOTBIMg2pPgKOBdDB3SowCcf

CSeq: 124 INVITE

Allow: INVITE, ACK, BYE, CANCEL, UPDATE

Supported: 

Content-Type: application/sdp

Content-Length:   269



v=0

o=- 3881484276 3881484276 IN IP4 172.17.0.2

s=pjmedia

t=0 0

m=audio 4000 RTP/AVP 0 8 96

c=IN IP4 172.17.0.2

b=TIAS:64000

a=rtcp:4001 IN IP4 172.17.0.2

a=sendrecv

a=rtpmap:0 PCMU/8000

a=rtpmap:8 PCMA/8000

a=rtpmap:96 telephone-event/8000

a=fmtp:96 0-16


--end msg--

14:04:36.828      tsx0x61d000000b28  ...State changed from Null to Calling, event=TX_MSG
14:04:36.828      dlg0x61d000000128  ....Transaction tsx0x61d000000b28 state changed to Calling
14:04:36.828             simpleua.c  .....Call state changed to CALLING

14:04:37.328      tsx0x61d000000b28  Retransmit timer event
14:04:37.328      tsx0x61d000000b28  .Retransmiting Request msg INVITE/cseq=124 (tdta0x62100001b9a8), count=0, restart?=1
14:04:37.328             simpleua.c  .TX 724 bytes Request msg INVITE/cseq=124 (tdta0x62100001b9a8) to UDP 127.0.0.1:5061:
INVITE sip:user@127.0.0.1:5061 SIP/2.0

Via: SIP/2.0/UDP 172.17.0.2:5060;rport;branch=z9hG4bKPjiNeUsXjdMuRBU2j.KGSI94O1i7pQoYqc

Max-Forwards: 70

From: <sip:simpleuac@172.17.0.2>;tag=PKcMBzp6yhIZQG-du1TsYkW1MPmX6L5V

To: sip:user@127.0.0.1

Contact: <sip:simpleuac@172.17.0.2:5060>

Call-ID: 2mdIf8lexOTBIMg2pPgKOBdDB3SowCcf

CSeq: 124 INVITE

Allow: INVITE, ACK, BYE, CANCEL, UPDATE

Supported: 

Content-Type: application/sdp

Content-Length:   269



v=0

o=- 3881484276 3881484276 IN IP4 172.17.0.2

s=pjmedia

t=0 0

m=audio 4000 RTP/AVP 0 8 96

c=IN IP4 172.17.0.2

b=TIAS:64000

a=rtcp:4001 IN IP4 172.17.0.2

a=sendrecv

a=rtpmap:0 PCMU/8000

a=rtpmap:8 PCMA/8000

a=rtpmap:96 telephone-event/8000

a=fmtp:96 0-16


--end msg--

14:04:37.329         sip_endpoint.c  Processing incoming message: Response msg 180/INVITE/cseq=124 (rdata0x625000000128)
14:04:37.329             simpleua.c  .RX 491 bytes Response msg 180/INVITE/cseq=124 (rdata0x625000000128) from UDP 127.0.0.1:5061:
SIP/2.0 180 Ringing

Via: SIP/2.0/UDP 172.17.0.2:5060;branch=z9hG4bKPjiNeUsXjdMuRBU2j.KGSI94O1i7pQoYqc;rport=5060;received=127.0.0.1

From: <sip:simpleuac@172.17.0.2>;tag=PKcMBzp6yhIZQG-du1TsYkW1MPmX6L5V

To: sip:user@127.0.0.1;tag=a3a2b879344c05f7

Call-ID: 2mdIf8lexOTBIMg2pPgKOBdDB3SowCcf

CSeq: 124 INVITE

Server: baresip v0.6.2 (x86_64/linux)

Contact: <sip:user-0x2552320@127.0.0.1:5061>

Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,NOTIFY,SUBSCRIBE,INFO,MESSAGE,REFER

Content-Length: 0




--end msg--
14:04:37.329      tsx0x61d000000b28  .Incoming Response msg 180/INVITE/cseq=124 (rdata0x625000000128) in state Calling
14:04:37.329      tsx0x61d000000b28  ..State changed from Calling to Proceeding, event=RX_MSG
14:04:37.329      dlg0x61d000000128  ...Received Response msg 180/INVITE/cseq=124 (rdata0x625000000128)
14:04:37.330      dlg0x61d000000128  ....Route-set updated
14:04:37.330      dlg0x61d000000128  ...Transaction tsx0x61d000000b28 state changed to Proceeding
14:04:37.330             simpleua.c  ....Call state changed to EARLY

14:04:37.330         sip_endpoint.c  Processing incoming message: Response msg 200/INVITE/cseq=124 (rdata0x625000007928)
14:04:37.330             simpleua.c  .RX 846 bytes Response msg 200/INVITE/cseq=124 (rdata0x625000007928) from UDP 127.0.0.1:5061:
SIP/2.0 200 Answering

Via: SIP/2.0/UDP 172.17.0.2:5060;branch=z9hG4bKPjiNeUsXjdMuRBU2j.KGSI94O1i7pQoYqc;rport=5060;received=127.0.0.1

From: <sip:simpleuac@172.17.0.2>;tag=PKcMBzp6yhIZQG-du1TsYkW1MPmX6L5V

To: sip:user@127.0.0.1;tag=5326e903b0627b77

Call-ID: 2mdIf8lexOTBIMg2pPgKOBdDB3SowCcf

CSeq: 124 INVITE

Server: baresip v0.6.2 (x86_64/linux)

Contact: <sip:user-0x117e010@127.0.0.1:5061>

Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,NOTIFY,SUBSCRIBE,INFO,MESSAGE,REFER

Content-Type: application/sdp

Content-Length: 320


jv=0

o=- 2171053277 1572505827 IN IP4 127.0.0.1

s=-

c=IN IP4 127.0.0.1

t=0 0

a=tool:baresip 0.6.2

m=audio 47698 RTP/AVP 0 8 96

a=rtpmap:0 PCMU/8000

a=rtpmap:8 PCMA/8000

a=rtpmap:96 telephone-event/8000

a=fmtp:96 0-15

a=sendrecv

a=label:1

a=rtcp-rsize

a=ssrc:2304287767 cname:sip:user@127.0.0.1

a=ptime:20


--end msg--
14:04:37.330      tsx0x61d000000b28  .Incoming Response msg 200/INVITE/cseq=124 (rdata0x625000007928) in state Proceeding
14:04:37.330      tsx0x61d000000b28  ..State changed from Proceeding to Terminated, event=RX_MSG
14:04:37.330         sip_ua_layer.c  ...Received forked Response msg 200/INVITE/cseq=124 (rdata0x625000007928) for existing dialog dlg0x61d000000128
14:04:37.330         sip_ua_layer.c  ...Unhandled forked Response msg 200/INVITE/cseq=124 (rdata0x625000007928) from 127.0.0.1:5061, response will be handed over to the first dialog
14:04:37.330      dlg0x61d000000128  ...Received Response msg 200/INVITE/cseq=124 (rdata0x625000007928)
14:04:37.330      dlg0x61d000000128  ....Route-set updated
14:04:37.330      dlg0x61d000000128  ....Route-set frozen
14:04:37.330      dlg0x61d000000128  ...Transaction tsx0x61d000000b28 state changed to Terminated
14:04:37.330             simpleua.c  ....Call state changed to CONNECTING
14:04:37.330                  sdp.c  ....Error parsing SDP in line 1 col 0: Success

simpleua: ../src/pjmedia/sdp.c:1445: pj_status_t pjmedia_sdp_parse(pj_pool_t *, char *, pj_size_t, pjmedia_sdp_session **): Assertion `ctx.last_error != PJ_SUCCESS' failed.


************************************Call Stack************************************

#0  0x00007f85434f5438 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
        resultvar = 0
        pid = 9
        selftid = 9
#1  0x00007f85434f703a in __GI_abort () at abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x4, sa_sigaction = 0x4}, sa_mask = {__val = {0, 0, 140733612230016, 47244640256, 
              140210359287808, 5584913, 1445, 5584542, 11559904, 11548200, 140210336974220, 140210338071376, 140210338085024, 0, 
              140210338071376, 5584913}}, sa_flags = 1151909888, sa_restorer = 0x553811}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007f85434edbe7 in __assert_fail_base (fmt=<optimized out>, assertion=assertion@entry=0x553811 "ctx.last_error != PJ_SUCCESS", 
    file=file@entry=0x552e55 "../src/pjmedia/sdp.c", line=line@entry=1445, 
    function=function@entry=0x55369e "pj_status_t pjmedia_sdp_parse(pj_pool_t *, char *, pj_size_t, pjmedia_sdp_session **)") at assert.c:92
        str = 0xb25bd0 "xK\210C\205\177"
        total = 4096
#3  0x00007f85434edc92 in __GI___assert_fail (assertion=0x553811 "ctx.last_error != PJ_SUCCESS", file=0x552e55 "../src/pjmedia/sdp.c", 
    line=1445, function=0x55369e "pj_status_t pjmedia_sdp_parse(pj_pool_t *, char *, pj_size_t, pjmedia_sdp_session **)") at assert.c:101
No locals.
#4  0x00000000004708a5 in pjmedia_sdp_parse (pool=<optimized out>, buf=<optimized out>, len=<optimized out>, p_sdp=0xb063e0)
    at ../src/pjmedia/sdp.c:1445
        errmsg = "Success\000x\304\261\000\000\000\000\000 ^\260\000\000\000\000\000\370a\260\000\000\000\000\000\004\000\000\000\000\000\000\000+tT\000\000\000\000\000\005\000\000\000\000\000\000\000+tT\000\000\000\000\000\005\000\000\000\000\000\000\000\000Hx\000\000\000\000"
        cur_name = <optimized out>
        scanner = <optimized out>
        pj_x_except__ = <optimized out>
        pj_x_code__ = <optimized out>
        media = <optimized out>
#5  0x0000000000406bf6 in pjsip_rdata_get_sdp_info (rdata=0xb045b8) at ../src/pjsip-ua/sip_inv.c:982
        status = <optimized out>
        sdp_info = <optimized out>
        ctype_hdr = <optimized out>
        body = 0xb062d0
---Type <return> to continue, or q <return> to quit---
        app_sdp = <optimized out>
#6  0x000000000040ed32 in inv_check_sdp_in_incoming_msg (inv=<optimized out>, tsx=0xb21918, rdata=0xb045b8)
    at ../src/pjsip-ua/sip_inv.c:1987
        msg = 0xb058b0
        sdp_info = <optimized out>
        tsx_inv_data = <optimized out>
        status = <optimized out>
#7  0x0000000000412cb6 in inv_on_state_early (inv=0xb1de68, e=0x7fff18f70ab0) at ../src/pjsip-ua/sip_inv.c:4469
        status = <optimized out>
        tsx = 0xb21918
        dlg = <optimized out>
#8  0x000000000040ea9e in mod_inv_on_tsx_state (tsx=0xb21918, e=0x7fff18f70ab0) at ../src/pjsip-ua/sip_inv.c:718
        dlg = <optimized out>
        inv = 0xb1de68
#9  0x0000000000463506 in pjsip_dlg_on_tsx_state (dlg=0xb1c478, tsx=0xb21918, e=0x7fff18f70ab0) at ../src/pjsip/sip_dialog.c:2069
        i = 0
#10 0x0000000000466645 in mod_ua_on_tsx_state (tsx=0x7f85434f5438 <__GI_raise+56>, e=0x0) at ../src/pjsip/sip_ua_layer.c:178
        dlg = 0x9
#11 0x0000000000455f07 in tsx_set_state (tsx=0xb21918, state=<optimized out>, event_src_type=PJSIP_EVENT_RX_MSG, event_src=<optimized out>, 
    flag=<optimized out>) at ../src/pjsip/sip_transaction.c:1253
        prev_state = <optimized out>
#12 0x00000000004587e4 in tsx_on_state_proceeding_uac (tsx=0xb21918, event=0x7fff18f70b70) at ../src/pjsip/sip_transaction.c:3016
No locals.
#13 0x000000000045693e in pjsip_tsx_recv_msg (tsx=0xb21918, rdata=0xb045b8) at ../src/pjsip/sip_transaction.c:1832
        event = {prev = 0x7fff18f70b70, next = 0xfefefefefefefeff, type = PJSIP_EVENT_TIMER, body = {timer = {entry = 0x8}, tsx_state = {
              src = {rdata = 0x8, tdata = 0x8, timer = 0x8, status = 8, data = 0x8}, tsx = 0x206, prev_state = -4, type = 4294967295}, 
            tx_msg = {tdata = 0x8}, tx_error = {tdata = 0x8, tsx = 0x206}, rx_msg = {rdata = 0x8}, user = {user1 = 0x8, user2 = 0x206, 
              user3 = 0xfffffffffffffffc, user4 = 0xb045b8}}}
#14 0x0000000000457821 in mod_tsx_layer_on_rx_response (rdata=0xb045b8) at ../src/pjsip/sip_transaction.c:893
        hval = <optimized out>
        key = <optimized out>
#15 0x0000000000439e57 in pjsip_endpt_process_rx_data (endpt=<optimized out>, rdata=0xb045b8, p=0x7fff18f70c90, p_handled=<optimized out>)
---Type <return> to continue, or q <return> to quit---
    at ../src/pjsip/sip_endpoint.c:901
        handled = 0
        def_prm = <optimized out>
        msg = <optimized out>
        mod = 0x785030 <mod_tsx_layer>
        status = <optimized out>
#16 0x0000000000438cb1 in endpt_on_rx_msg (endpt=0xaef168, status=0, rdata=0xb045b8) at ../src/pjsip/sip_endpoint.c:1043
        handled = 0
        proc_prm = {start_prio = 0, start_mod = 0x0, idx_after_start = 0, silent = 1}
#17 0x0000000000447b82 in pjsip_tpmgr_receive_packet (mgr=<optimized out>, rdata=0xb045b8) at ../src/pjsip/sip_transport.c:2026
        end = <optimized out>
        saved = <optimized out>
        msg = <optimized out>
        p = <optimized out>
        msg_fragment_size = <optimized out>
        total_processed = 0
        remaining_len = <optimized out>
        tr = 0xb02528
        current_pkt = <optimized out>
#18 0x000000000044c0ae in udp_on_read_complete (key=<optimized out>, op_key=<optimized out>, bytes_read=<optimized out>)
    at ../src/pjsip/sip_transport_udp.c:192
        src_addr = 0xb056a8
        size_eaten = <optimized out>
        flags = <optimized out>
        rdata = 0xb045b8
        tp = 0xb02528
        i = <optimized out>
        status = <optimized out>
#19 0x00000000005207e9 in ioqueue_dispatch_read_event (ioqueue=0xafa150, h=0xafac40) at ../src/pj/ioqueue_common_abs.c:605
        bytes_read = 6
        has_lock = 0
        rc = <optimized out>
---Type <return> to continue, or q <return> to quit---
#20 0x000000000052475f in pj_ioqueue_poll (ioqueue=<optimized out>, timeout=<optimized out>) at ../src/pj/ioqueue_select.c:1070
        event = {{key = 0xafac40, event_type = READABLE_EVENT}, {key = 0x7fff18f71058, event_type = NO_EVENT}, {key = 0x0, 
            event_type = 418844784}, {key = 0x7fff00000000, event_type = NO_EVENT}, {key = 0x0, event_type = 32}, {key = 0x0, 
            event_type = NO_EVENT}, {key = 0x7fff18f71080, event_type = NO_EVENT}, {key = 0x10, event_type = 6}, {key = 0x7fff18f714b2, 
            event_type = 11}, {key = 0x544953, event_type = READABLE_EVENT}, {key = 0x7fff18f710d0, event_type = NO_EVENT}, {
            key = 0xffffffffffffffff, event_type = NO_EVENT}, {key = 0x0, event_type = 5523795}, {key = 0x0, event_type = 4}, {
            key = 0x55292f, event_type = 8000}, {key = 0x0, event_type = NO_EVENT}}
        rfdset = <optimized out>
        wfdset = <optimized out>
        xfdset = <optimized out>
        nfds = <optimized out>
        count = <optimized out>
        event_cnt = 1
        h = <optimized out>
#21 0x0000000000439788 in pjsip_endpt_handle_events2 (endpt=0xaef168, max_timeout=0x7fff18f717a0, p_count=0x0)
    at ../src/pjsip/sip_endpoint.c:744
        net_event_count = 0
        count = 0
        timeout = {sec = 140733612234544, msec = -72340172838076673}
        c = <optimized out>
#22 0x00000000004048fb in main (argc=2, argv=0x7fff18f719b8) at ../src/samples/simpleua.c:552
        timeout = {sec = 0, msec = 10}
        status = <optimized out>
```

**Comment by sauwming** [comment]
PJSIP 2.8 is rather old. Please confirm if the issue still happens with the latest version, and we'll check.

**Comment by Kexin6** [comment]
I apologize for the delayed response. This issue does not exist in the latest version. Thank you!!
