### ISSUE TITLE
Assertion error `pool && rhs' failed in sdp.c:pjmedia_sdp_session_clone() when using sipecho

### ISSUE THREAD

**Issue by Kexin6** [pjsip/pjproject#3367]
### Describe the bug

The assertion error described in the title occurred when PJSIP's Echo service processed and created an echoing response for an incoming INVITE message, specifically in the `sipecho.c:create_answer()` function.

### Steps to reproduce

1. Compile PJSIP binaries under pjproject directory: `./configure --disable-strip CFLAGS=-g && make dep && make clean && make`

2. Compile Baresip binary under baresip directory: `make -C deps/re install PREFIX=$PWD/bin && make -C deps/rem install PREFIX=$PWD/bin LIBRE_MK=$SIP_FUZZER_DIR/baresip/deps/re/mk/re.mk && make PREFIX=$PWD/bin LIBRE_MK=deps/re/mk/re.mk LIBRE_INC=bin/include/re/ LIBRE_SO=bin/lib/ LIBREM_PATH=bin/ install`

3. Launch SIP Echo service: .`/pjproject/pjsip-apps/bin/samples/x86_64-unknown-linux-gnu/sipecho`

4. Launch Baresip client: `./baresip -f docs/examples -e \"d test@127.0.0.1:5060\" -n 127.0.0.1"`

5. Baresip sends the following INVITE message to the SIP Echo application:

```
	INVITE sip:test@127.0.0.1:5060 SIP/2.0\r\n
	Via: SIP/2.0/UDP 127.0.0.1:42401;branch=z9hG4bKc4f96e916af2806f;rport\r\n
	Contact: <sip:user-0x1731320@127.0.0.1:42401>\r\n
	Max-Forwards: 70\r\n
	To: <sip:test@127.0.0.1:5060>\r\n
	From: <sip:user@example.com>;tag=282b71c65f7aea57\r\n
	Call-ID: 881adcccf2eb3ef2\r\n
	CSeq: 16329 INVITE\r\n
	User-Agent: baresip v0.6.2 (x86_64/linux)\r\n
	Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,NOTIFY,SUBSCRIBE,INFO,MESSAGE,REFER\r\n
	Supported: gruu\r\n
	Content-Type: application/sdp\r\nContent-Length: 276\r\n\r\n
	v=0\r\n
	o=- 59939733 143568415 IN IP4 127.0.0.1\r\n
	s=-\r\n
	c=IN IP4 127.0.0.1\r\n
	t=0 0\r\n
	a=tool:baresip 0.6.2\r\n
	m=audio 15616 RTP/AVP 0 8 101\r\n
	a=rtpmap:0 PCMU/8000\r\n
	a=rtpmap:8 PCMA/8000\r\n
	a=rtpmap:101 telephone-event/8000\r\n
	a=fmtp:101 0-15\r\n
	a=sendrecv\r\n
	a=label:1\r\n
	a=rtcp-rsize\r\n
	a=ptime:20\r\n
```

6. SIP Echo application hits the assertion error `'pool && rhs' failed` in `sdp.c`.

### PJSIP version

2.13, 2.8

### Context

At first, Baresip sends an INVITE message as described in _Steps to Reproduce_, and sipecho responds with status code 400 (Please check _Log, call stack, etc._ for more details):
```
    sdp_info = pjsip_rdata_get_sdp_info(rdata);
    if (!sdp_info || !sdp_info->sdp) {
	pj_str_t reason = pj_str("Require valid offer");
	pjsip_endpt_respond_stateless( app.sip_endpt, rdata,
				       400, &reason,
				       NULL, NULL);
    }
```

Upon further investigation, we determined that the error occurred when the "offer" variable passed to the `create_answer()` function is NULL:
`pjmedia_sdp_session *answer = pjmedia_sdp_session_clone(pool, offer);`

I think the root cause is the sipecho application not properly returning the pj status in the `on_rx_request()` function when it failed to parse the SDP body or found a missing body.

To resolve this issue, we suggest adding the line `return PJ_TRUE;` immediately after sipecho service responds to the invalid incoming message with status 400. Please refer to the attached patch for more details. 

[0001-return-pj-status-properly-with-response-400.txt](https://github.com/pjsip/pjproject/files/10669304/0001-return-pj-status-properly-with-response-400.txt)
(There is something wrong with submitting .patch file on GitHub. I apologize for this inconvenience.)
Thanks for checking!

### Log, call stack, etc

```shell
#1  0x0000000000473e33 in pjmedia_sdp_session_clone (pool=0x7f97940008c0, rhs=0x0) at ../src/pjmedia/sdp.c:1495
#2  0x00000000004049b3 in create_answer (call_num=0, pool=0x7f97940008c0, offer=0xb) at ../src/samples/sipecho.c:330
#3  0x0000000000405c11 in on_rx_request (rdata=0x11865a8) at ../src/samples/sipecho.c:505
#4  0x000000000043a337 in pjsip_endpt_process_rx_data (endpt=<optimized out>, rdata=0x11865a8, p=0x7f979c6e7410, p_handled=<optimized out>)
    at ../src/pjsip/sip_endpoint.c:893
#5  0x00000000004390df in endpt_on_rx_msg (endpt=0x1171378, status=0, rdata=0x11865a8) at ../src/pjsip/sip_endpoint.c:1043
#6  0x0000000000449563 in pjsip_tpmgr_receive_packet (mgr=<optimized out>, rdata=0x11865a8) at ../src/pjsip/sip_transport.c:1978
#7  0x000000000044d623 in udp_on_read_complete (key=<optimized out>, op_key=<optimized out>, bytes_read=<optimized out>)
    at ../src/pjsip/sip_transport_udp.c:192
#8  0x0000000000491548 in ioqueue_dispatch_read_event (ioqueue=0x117c150, h=0x117cc40) at ../src/pj/ioqueue_common_abs.c:605
#9  0x0000000000495569 in pj_ioqueue_poll (ioqueue=<optimized out>, timeout=<optimized out>) at ../src/pj/ioqueue_select.c:1070
#10 0x0000000000439bbc in pjsip_endpt_handle_events2 (endpt=0x1171378, max_timeout=0x7f979c6e7f10, p_count=0x0) at ../src/pjsip/sip_endpoint.c:744
#11 0x0000000000404925 in worker_proc (arg=<optimized out>) at ../src/samples/sipecho.c:167
#12 0x0000000000497390 in thread_main (param=0x1171168) at ../src/pj/os_core_unix.c:541
#13 0x00007f979ced06ba in start_thread (arg=0x7f979c6e8700) at pthread_create.c:333
#14 0x00007f979cc0651d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

************************************lOG************************************
Client message:
	INVITE sip:test@127.0.0.1:5060 SIP/2.0\r\n
	Via: SIP/2.0/UDP 127.0.0.1:42401;branch=z9hG4bKc4f96e916af2806f;rport\r\n
	Contact: <sip:user-0x1731320@127.0.0.1:42401>\r\n
	Max-Forwards: 70\r\n
	To: <sip:test@127.0.0.1:5060>\r\n
	From: <sip:user@example.com>;tag=282b71c65f7aea57\r\n
	Call-ID: 881adcccf2eb3ef2\r\n
	CSeq: 16329 INVITE\r\n
	User-Agent: baresip v0.6.2 (x86_64/linux)\r\n
	Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,NOTIFY,SUBSCRIBE,INFO,MESSAGE,REFER\r\n
	Supported: gruu\r\n
	Content-Type: application/sdp\r\nContent-Length: 276\r\n\r\n
	v=0\r\n
	o=- 59939733 143568415 IN IP4 127.0.0.1\r\n
	s=-\r\n
	c=IN IP4 127.0.0.1\r\n
	t=0 0\r\n
	a=tool:baresip 0.6.2\r\n
	m=audio 15616 RTP/AVP 0 8 101\r\n
	a=rtpmap:0 PCMU/8000\r\n
	a=rtpmap:8 PCMA/8000\r\n
	a=rtpmap:101 telephone-event/8000\r\n
	a=fmtp:101 0-15\r\n
	a=sendrecv\r\n
	a=label:1\r\n
	a=rtcp-rsize\r\n
	a=ptime:20\r\n

SIP Echo Server response:
	SIP/2.0 400 Require valid offer\r\n
	Via: SIP/2.0/UDP 127.0.0.1:52143;rport=42401;received=127.0.0.1;branch=z9hG4bK885296ecccb6bfc5\r\n
	Call-ID: f5acadcaba27a3bf\r\n
	From: <sip:user@example.com>;tag=517e5b87e9e5b348\r\n
	To: <sip:test@127.0.0.1>;tag=z9hG4bK885296ecccb6bfc5\r\n
	CSeq: 26541 INVITE\r\n
	Content-Length:  0\r\n
```

**Comment by trengginas** [comment]
This looks valid. You can create a PR for this issue.

**Comment by Kexin6** [comment]
PR #3369 submitted :+1:
