### ISSUE TITLE
pjsip_parse_uri SEGV on unknown address

### ISSUE THREAD

**Issue by 0x34d** [pjsip/pjproject#3432]
### Describe the bug

SEGV  Error while testing `pjsip_parse_uri`

### Steps to reproduce

https://github.com/0x34d/pjproject/tree/oss-fuzz-Ideal

### PJSIP version

2.13

### Log, call stack, etc

```shell
AddressSanitizer:DEADLYSIGNAL
=================================================================
==408961==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000100 (pc 0x00000059d6c1 bp 0x7ffc0e0457b0 sp 0x7ffc0e045790 T0)
==408961==The signal is caused by a READ memory access.
==408961==Hint: address points to the zero page.
    #0 0x59d6c1 in pj_scan_peek /home/oblivion/project/pjsip/pjlib-util/build/../src/pjlib-util/scanner.c:223:5
    #1 0x575371 in int_parse_uri_or_name_addr /home/oblivion/project/pjsip/pjsip/build/../src/pjsip/sip_parser.c:1423:19
    #2 0x5750c3 in pjsip_parse_uri /home/oblivion/project/pjsip/pjsip/build/../src/pjsip/sip_parser.c:966:15
    #3 0x56fb22 in uri_parse /home/oblivion/project/pjsip/tests/fuzz/fuzz-uri.c:50:11
    #4 0x56fb22 in LLVMFuzzerTestOneInput /home/oblivion/project/pjsip/tests/fuzz/fuzz-uri.c:91:11
    #5 0x4535a1 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/oblivion/project/pjsip/tests/fuzz/fuzz-uri+0x4535a1) (BuildId: 16d81df49466ee28c65376d3617b94c26b647412)
    #6 0x453ef0 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*) (/home/oblivion/project/pjsip/tests/fuzz/fuzz-uri+0x453ef0) (BuildId: 16d81df49466ee28c65376d3617b94c26b647412)
    #7 0x454f40 in fuzzer::Fuzzer::MutateAndTestOne() (/home/oblivion/project/pjsip/tests/fuzz/fuzz-uri+0x454f40) (BuildId: 16d81df49466ee28c65376d3617b94c26b647412)
    #8 0x456947 in fuzzer::Fuzzer::Loop(std::vector<fuzzer::SizedFile, std::allocator<fuzzer::SizedFile>>&) (/home/oblivion/project/pjsip/tests/fuzz/fuzz-uri+0x456947) (BuildId: 16d81df49466ee28c65376d3617b94c26b647412)
    #9 0x43aefc in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/oblivion/project/pjsip/tests/fuzz/fuzz-uri+0x43aefc) (BuildId: 16d81df49466ee28c65376d3617b94c26b647412)
    #10 0x42aba6 in main (/home/oblivion/project/pjsip/tests/fuzz/fuzz-uri+0x42aba6) (BuildId: 16d81df49466ee28c65376d3617b94c26b647412)
    #11 0x7f6711e1750f in __libc_start_call_main (/lib64/libc.so.6+0x2750f) (BuildId: 81daba31ee66dbd63efdc4252a872949d874d136)
    #12 0x7f6711e175c8 in __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x275c8) (BuildId: 81daba31ee66dbd63efdc4252a872949d874d136)
    #13 0x42abe4 in _start (/home/oblivion/project/pjsip/tests/fuzz/fuzz-uri+0x42abe4) (BuildId: 16d81df49466ee28c65376d3617b94c26b647412)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/oblivion/project/pjsip/pjlib-util/build/../src/pjlib-util/scanner.c:223:5 in pj_scan_peek
==408961==ABORTING
````
```

**Comment by sauwming** [comment]
You need to initialize the sip parser first.

Attached is the patch:
[fuzz-uri_fix.txt](https://github.com/pjsip/pjproject/files/10950991/fuzz-uri_fix.txt)
