### ISSUE TITLE
dial_dtmf Invalid value or argument (PJ_EINVAL)

### ISSUE THREAD

**Issue by TerehinAV** [pjsip/pjproject#3464]
### Describe the bug

Hi! I'm using pjsua v2.9 in python and trying to send dtmf in RFC 2833 payload format. But when I called dial_dtmf method, I've got an error: operation=dial_dtmf(), error=invalid value or argument (PJ_EINVAL)'
According to source code, digits argument should be a string_digits. But I have tried any options, even int. Nothing changed, I still have an error.
Perhaps, I need to rebuild lib with some fixes, but I have no idea what to edit.
And unfortunately, I didn't find any issue reports about this problem.
I'll be appreciated for any help in solving this problem.

p.s. _pjsua.call_dial_dtmf(self._id, digits) returns err 70004 with valid digit string like '1'
p.p.s. in 2.12.1 I got similar error when I tried to do the same

### Steps to reproduce
2.9:

dtmf to send: "#6666"

https://github.com/pjsip/pjproject/blob/master/pjsip-apps/src/python/samples/call.py
Update on_incoming_call like this:

```
import pjsua as pj
...
class MyAccountCallback(pj.AccountCallback):
    ...
    def on_incoming_call(self, call):
        ...
       call.answer(200)
       call.dial_dtmf('11')
       call.dial_dtmf('6')
       call.dial_dtmf('6')
       call.dial_dtmf('6')
       call.dial_dtmf('6')
```

And make some call.

2.12.1:
```
import pjsua2 as pj
...
class Account(pj.Account):
    ...
    def onIncomingCall(self, prm):
        call_id = prm.callId
        call = pj.Call(self, call_id)
        prm = pj.CallOpParam()
        prm.statusCode = pj.PJSIP_SC_OK
        call.answer(prm)
        call.dialDtmf("11")
```

### PJSIP version

2.9

### Context

Operating System: CentOS Linux 7 (Core)
Kernel: Linux 3.10.0-1160.53.1.el7.x86_64
Architecture: x86-64

### Log, call stack, etc
2.9:

```shell
Traceback (most recent call last):
  File "/opt/python3.7/lib64/python3.7/site-packages/pjsua.py", line 2898, in _cb_on_incoming_call
    _lib._cb_on_incoming_call(acc_id, call_id, rdata)
  File "/opt/python3.7/lib64/python3.7/site-packages/pjsua.py", line 2780, in _cb_on_incoming_call
    acc._cb.on_incoming_call( Call(self, call_id) )
  File "/.../CGS/domain/sip/callback/account.py", line 82, in on_incoming_call
    call.dial_dtmf(int('11'))
  File "/opt/python3.7/lib64/python3.7/site-packages/pjsua.py", line 1761, in dial_dtmf
    self._lib()._err_check("dial_dtmf()", self, err)
  File "/opt/python3.7/lib64/python3.7/site-packages/pjsua.py", line 2722, in _err_check
    raise Error(op_name, obj, err_code, err_msg)
pjsua.Error: Object: {Call <sip:...@...>}, operation=dial_dtmf(), error=b'Invalid value or argument (PJ_EINVAL)'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/python3.7/lib64/python3.7/site-packages/pjsua.py", line 2895, in _cb_on_call_state
    _lib._cb_on_call_state(call_id)
  File "/opt/python3.7/lib64/python3.7/site-packages/pjsua.py", line 2787, in _cb_on_call_state
    call = self._lookup_call(call_id)
  File "/opt/python3.7/lib64/python3.7/site-packages/pjsua.py", line 2738, in _lookup_call
    return _pjsua.call_get_user_data(call_id)
SystemError: <built-in function call_get_user_data> returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/python3.7/lib64/python3.7/site-packages/pjsua.py", line 2901, in _cb_on_call_media_state
    _lib._cb_on_call_media_state(call_id)
  File "/opt/python3.7/lib64/python3.7/site-packages/pjsua.py", line 2799, in _cb_on_call_media_state
    call = self._lookup_call(call_id)
  File "/opt/python3.7/lib64/python3.7/site-packages/pjsua.py", line 2738, in _lookup_call
    return _pjsua.call_get_user_data(call_id)
SystemError: <built-in function call_get_user_data> returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/python3.7/lib64/python3.7/site-packages/pjsua.py", line 2895, in _cb_on_call_state
    _lib._cb_on_call_state(call_id)
  File "/opt/python3.7/lib64/python3.7/site-packages/pjsua.py", line 2787, in _cb_on_call_state
    call = self._lookup_call(call_id)
  File "/opt/python3.7/lib64/python3.7/site-packages/pjsua.py", line 2738, in _lookup_call
    return _pjsua.call_get_user_data(call_id)
SystemError: <built-in function call_get_user_data> returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/python3.7/lib64/python3.7/site-packages/pjsua.py", line 2895, in _cb_on_call_state
    _lib._cb_on_call_state(call_id)
  File "/opt/python3.7/lib64/python3.7/site-packages/pjsua.py", line 2787, in _cb_on_call_state
    call = self._lookup_call(call_id)
  File "/opt/python3.7/lib64/python3.7/site-packages/pjsua.py", line 2738, in _lookup_call
    return _pjsua.call_get_user_data(call_id)
SystemError: <built-in function call_get_user_data> returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/python3.7/lib64/python3.7/site-packages/pjsua.py", line 2895, in _cb_on_call_state
    _lib._cb_on_call_state(call_id)
  File "/opt/python3.7/lib64/python3.7/site-packages/pjsua.py", line 2787, in _cb_on_call_state
    call = self._lookup_call(call_id)
  File "/opt/python3.7/lib64/python3.7/site-packages/pjsua.py", line 2738, in _lookup_call
    return _pjsua.call_get_user_data(call_id)
SystemError: <built-in function call_get_user_data> returned a result with an error set
```

2.12.1:
```
13:14:03.472            pjsua_aud.c !...Call 1 dialing DTMF 11
13:14:03.473            pjsua_aud.c  ....Media is not established yet!
13:14:03.473               call.cpp  ...pjsua_call_dial_dtmf(id, &pj_digits) error: Invalid operation (PJ_EINVALIDOP) (status=70013) [../src/pjsua2/call.cpp:782]
bash: line 1: 94082 Segmentation fault      (core dumped) env "JETBRAINS_REMOTE_RUN"="1" "LIBRARY_ROOTS"="C:/Users/av.terehin/.PyCharm2018.2/system/remote_sources/-1667105006/737528954;C:/Users/av.terehin/.PyCharm2018.2/system/remote_sources/-1667105006/1118575588;C:/Users/av.terehin/.PyCharm2018.2/system/remote_sources/-1667105006/541436894;C:/Users/av.terehin/.PyCharm2018.2/system/remote_sources/-1667105006/-486040096;C:/Users/av.terehin/.PyCharm2018.2/system/python_stubs/-1667105006;C:/Program Files/JetBrains/PyCharm 2018.2.8/helpers/python-skeletons;C:/Program Files/JetBrains/PyCharm 2018.2.8/helpers/typeshed/stdlib/3.4;C:/Program Files/JetBrains/PyCharm 2018.2.8/helpers/typeshed/stdlib/3;C:/Program Files/JetBrains/PyCharm 2018.2.8/helpers/typeshed/stdlib/2and3;C:/Program Files/JetBrains/PyCharm 2018.2.8/helpers/typeshed/third_party/3;C:/Program Files/JetBrains/PyCharm 2018.2.8/helpers/typeshed/third_party/2and3" "PYDEVD_LOAD_VALUES_ASYNC"="True" "PYTHONPATH"="/home/asterisk/.pycharm_helpers/pycharm_matplotlib_backend:/home/asterisk/listener:/home/asterisk/listener/test/sipcalls:/home/asterisk/listener/services/pj_project/call_service:/home/asterisk/listener/services/pj_project/CGS:/home/asterisk/.pycharm_helpers/pydev:C:/Users/av.terehin/.PyCharm2018.2/system/cythonExtensions:/home/asterisk/listener/services/pj_project/CGS" "PYTHONIOENCODING"="UTF-8" "PYTHONDONTWRITEBYTECODE"="1" "IPYTHONENABLE"="True" "PYCHARM_MATPLOTLIB_PORT"="59426" "PYCHARM_HOSTED"="1" "PYTHONUNBUFFERED"="1" "IDE_PROJECT_ROOTS"="/home/asterisk/listener" '/bin/python3.5' '-u' '/home/asterisk/.pycharm_helpers/pydev/pydevd.py' '--multiproc' '--qt-support=auto' '--client' '0.0.0.0' '--port' '40011' '--file' '/home/asterisk/listener/services/pj_project/CGS/sandbox.py' '--debug'
```

**Comment by sauwming** [comment]
Currently the issue page is for bug report or feature request only.

You can try with the C sample app first, i.e. pjsua, to test the dtmf feature and see whether it works and what parameter it expects.
