### ISSUE TITLE
Make calling issue

### ISSUE THREAD

**Issue by Vivek09082000** [pjsip/pjproject#3685]
### Describe the bug

- When i call from Android version 9 to received from another device but after some time lagging and crash the app.
- We are calling from any other Android version device then Call is Disconnected and showing message is '**Not Acceptable Here**' from calling side and receiver side showing message is '**Request terminated**'.
- When i Call and WI Fi is connected then showing same error like described in second number point.

### Steps to reproduce

1. Initiate Call from device A to device B.
2. Call B is received but after some time lagging the app.
3. When B is called then calling is not working.

### PJSIP version

2.13.1

### Context

The issue is happened in All Android devices.

### Log, call stack, etc

```shell
-Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 20211 (FinalizerDaemon), pid 20189 (jsip.pjsua2.app)

-FATAL EXCEPTION: main
                                                    Process: com.dcs, PID: 9577
                                                    java.lang.NoSuchMethodError: no static method "Lorg/pjsip/pjsua2/pjsua2JNI;.SwigDirector_Call_onZrtpShowSAS(Lorg/pjsip/pjsua2/Call;J)V"
                                                    	at org.pjsip.pjsua2.pjsua2JNI.swig_module_init(Native Method)
                                                    	at org.pjsip.pjsua2.pjsua2JNI.<clinit>(pjsua2JNI.java:2902)
                                                    	at org.pjsip.pjsua2.pjsua2JNI.new_Endpoint(Native Method)
                                                    	at org.pjsip.pjsua2.Endpoint.<init>(Endpoint.java:69)
                                                    	at com.dcs.pjsip.pjsua2.app.MyApp.<clinit>(MyApp.java:80)
                                                    	at com.dcs.fragment.DialpadFragment.getDataCall(DialpadFragment.java:266)
                                                    	at com.dcs.fragment.DialpadFragment.onViewCreated(DialpadFragment.java:72)
                                                    	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
                                                    	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
                                                    	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
                                                    	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
                                                    	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
                                                    	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
                                                    	at android.os.Handler.handleCallback(Handler.java:873)
                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                    	at android.os.Looper.loop(Looper.java:233)
                                                    	at android.app.ActivityThread.main(ActivityThread.java:7212)
                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:499)
                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

**Comment by sauwming** [comment]
There seems to be a couple of issues here:
- The lag and crash
Figure out the cause of the lag. Is it the video (try without)? certain codec (try with another)? The crash seems to point out to ZRTP, which is not included in PJSIP.
- `'Not Acceptable Here'` means that the incoming call offer contains something that's not supported locally.

**Comment by Vivek09082000** [comment]
Hello Sir,

When i want to include ZRTP in PJSIP project then how to do this. What's the process of this so i can add this in my PJSIP project.

Thank you.

**Comment by sauwming** [comment]
You can add the implementation in pjmedia/arc/pjmedia. Check `transport_srtp.c` for reference.
Alternatively, you can use existing implementation by third party. The important thing here is that since it's a third party component, you need to be able to debug and fix it yourself if there's any issue.

Different platforms require different requirements. For example, video requirements are different on iOS and Android. Check the getting started doc for more details.
