### ISSUE TITLE
Python: module 'pjsua2' has no attribute 'AudioMediaPort'

### ISSUE THREAD

**Issue by mvaccaro-dev** [pjsip/pjproject#3697]
### Describe the bug

Missed AudioMediaPort on python porting

### Steps to reproduce

Installation
```shell
sudo apt-get install swig python3-dev
wget https://github.com/pjsip/pjproject/archive/refs/tags/2.13.1.tar.gz
tar -xf 2.13.1.tar.gz
cd pjproject-2.13.1
./configure --disable-video --disable-ffmpeg --disable-v4l2 CFLAGS="-fPIC" --disable-libwebrtc --disable-libsrtp
make dep & make
sudo make install

cd pjsip-apps/src/swig/python
make
make install
``` 

Testing
```shell
pi@raspberrypi:~ $ python
Python 3.9.2 (default, Mar 12 2021, 04:06:34)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pjsua2 as pj
>>> pj.AudioMediaPort
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pjsua2' has no attribute 'AudioMediaPort'
``` 

### PJSIP version

2.13.1

### Context

The issue happens on RPi 4

### Log, call stack, etc

```shell
pi@raspberrypi:~ $ python
Python 3.9.2 (default, Mar 12 2021, 04:06:34)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pjsua2 as pj
>>> pj.AudioMediaPort
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pjsua2' has no attribute 'AudioMediaPort'
```

**Comment by sauwming** [comment]
#3569 is not available in 2.13.1
