### ISSUE TITLE
the latest version pjsip2.14 run error

### ISSUE THREAD

**Issue by LoyaiHai** [pjsip/pjproject#3760]
### Describe the bug

I use ndk-r22b in ubuntu20.4, by compiling pjsip2.14 source code, first run: TARGET_ABI=armeabi-v7a APP_PLATFORM=android-21./configure-android. After compiling successfully, swig is executed to generate libpjsua2.so. Now porting to android studio, the following error occurs during initialization:
        UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__fwrite_chk" referenced by "/data/app/org.pjsip.pjsua2.app-1/lib/arm64/libpjsua2.so"...
        java.lang.UnsatisfiedLinkError: No implementation found for void org.pjsip.pjsua2.pjsua2JNI.swig_module_init() (tried Java_org_pjsip_pjsua2_pjsua2JNI_swig_1module_1init and Java_org_pjsip_pjsua2_pjsua2JNI_swig_1module_1init__)

### Steps to reproduce

I use ndk-r22b in ubuntu20.4, by compiling pjsip2.14 source code, first run: TARGET_ABI=armeabi-v7a APP_PLATFORM=android-21./configure-android. After compiling successfully, swig is executed to generate libpjsua2.so. Now porting to android studio, the following error occurs during initialization:
        UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__fwrite_chk" referenced by "/data/app/org.pjsip.pjsua2.app-1/lib/arm64/libpjsua2.so"...
        java.lang.UnsatisfiedLinkError: No implementation found for void org.pjsip.pjsua2.pjsua2JNI.swig_module_init() (tried Java_org_pjsip_pjsua2_pjsua2JNI_swig_1module_1init and Java_org_pjsip_pjsua2_pjsua2JNI_swig_1module_1init__)

### PJSIP version

2.14

### Context

Ubuntu 20.4
ndk: android-ndk-r22b

### Log, call stack, etc

```shell
2023-02-05 16:47:22.292 6659-6659/org.pjsip.pjsua2.app E/023===>: 开始加载===>pjsua2
2023-02-05 16:47:22.319 6659-6659/org.pjsip.pjsua2.app E/023===>: UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__fwrite_chk" referenced by "/data/app/org.pjsip.pjsua2.app-1/lib/arm64/libpjsua2.so"...
2023-02-05 16:47:22.319 6659-6659/org.pjsip.pjsua2.app E/art: No implementation found for void org.pjsip.pjsua2.pjsua2JNI.swig_module_init() (tried Java_org_pjsip_pjsua2_pjsua2JNI_swig_1module_1init and Java_org_pjsip_pjsua2_pjsua2JNI_swig_1module_1init__)
2023-02-05 16:47:22.320 6659-6659/org.pjsip.pjsua2.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.pjsip.pjsua2.app, PID: 6659
    java.lang.UnsatisfiedLinkError: No implementation found for void org.pjsip.pjsua2.pjsua2JNI.swig_module_init() (tried Java_org_pjsip_pjsua2_pjsua2JNI_swig_1module_1init and Java_org_pjsip_pjsua2_pjsua2JNI_swig_1module_1init__)
        at org.pjsip.pjsua2.pjsua2JNI.swig_module_init(Native Method)
        at org.pjsip.pjsua2.pjsua2JNI.<clinit>(pjsua2JNI.java:2930)
        at org.pjsip.pjsua2.Endpoint.<init>(Endpoint.java:81)
        at org.pjsip.pjsua2.app.MyApp.<clinit>(MyApp.java:345)
        at org.pjsip.pjsua2.app.MainActivity.onCreate(MainActivity.java:163)
        at android.app.Activity.performCreate(Activity.java:6309)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2530)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2665)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1499)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:207)
```

**Comment by LoyaiHai** [comment]
this question is close

**Comment by xreleven** [comment]
你这个问题解决了么？我现在也遇到这个问题，毫无头绪
![Uploading 1712108931172.jpg…]()
