### ISSUE TITLE
Loop transport does not work with PJSUA(2)

### ISSUE THREAD

**Issue by wosrediinanatour** [pjsip/pjproject#3771]
### Describe the bug

Commit [6dc9b8c181aff39845f02b4626e0812820d4ef0d ](https://github.com/pjsip/pjproject/commit/6dc9b8c181aff39845f02b4626e0812820d4ef0d) of https://github.com/pjsip/pjproject/security/advisories/GHSA-f76w-fh7c-pc66 cause loop transport to fail.

### Steps to reproduce

Make a call (cf. Context). 

### PJSIP version

2.14

### Context

- Linux
- Mocked pjsua_aud ("3rd party media stack")
- Using transport loop

### Log, call stack, etc

```shell
SDP negotiation done: Success 
...
Call 0: updating media.. 
...
Audio updated, stream #0: PCMU (sendrecv)
Media stream call00:1 is destroyed 
AddressSanitizer:DEADLYSIGNAL
=================================================================
==2193131==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000030 (pc 0x000001083a14 bp 0x000000000000 sp 0x7fae5b9e2290 T3)
==2193131==The signal is caused by a READ memory access.
==2193131==Hint: address points to the zero page.
    #0 0x1083a14 in grp_lock_dec_ref src/pj/lock.c:562:14
    #1 0x1083a14 in pj_grp_lock_dec_ref src/pj/lock.c:654:12
    #2 0x1046611 in transport_destroy src/pjmedia/transport_loop.c:254:5
    #3 0xfd7c0f in pjmedia_transport_close pjmedia/include/pjmedia/transport.h:1036:17
...
```

**Comment by sauwming** [comment]
Fixed by #3773
