### ISSUE TITLE
Loading the so file crashed

### ISSUE THREAD

**Issue by chenmingdu** [pjsip/pjproject#3888]
### Describe the bug

 java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "freeifaddrs" referenced by "/data/app/com.unionbroad.app-2/base.apk"...

### Steps to reproduce

Using the generated so file in the project, it crashes when loaded

### PJSIP version

2.13

### Context

android6.0    , use android-ndk-r20b and swig4.1 compile

### Log, call stack, etc

```shell
2024-03-18 13:14:19.977 6907-6907/com.unionbroad.app E/SipService: Error while loading PJSIP pjsua2 native library
    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "freeifaddrs" referenced by "/data/app/com.unionbroad.app-2/base.apk"...
        at java.lang.Runtime.loadLibrary(Runtime.java:372)
        at java.lang.System.loadLibrary(System.java:1076)
        at net.gotev.sipservice.SipService.loadNativeLibraries(SipService.java:1553)
        at net.gotev.sipservice.SipService.access$100(SipService.java:80)
        at net.gotev.sipservice.SipService$1.run(SipService.java:130)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5728)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
2024-03-18 13:14:20.138 6907-6907/com.unionbroad.app E/PTT-CrashHandle: ======== onCrashHandleStart =========
    crashType=0
    java.lang.UnsatisfiedLinkError
    dlopen failed: cannot locate symbol "freeifaddrs" referenced by "/data/app/com.unionbroad.app-2/base.apk"...
    java.lang.RuntimeException:java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "freeifaddrs" referenced by "/data/app/com.unionbroad.app-2/base.apk"...
    net.gotev.sipservice.SipService.loadNativeLibraries(SipService.java:1558)
    ......
    Caused by:
    java.lang.UnsatisfiedLinkError:dlopen failed: cannot locate symbol "freeifaddrs" referenced by "/data/app/com.unionbroad.app-2/base.apk"...
    java.lang.Runtime.loadLibrary(Runtime.java:372)
    java.lang.System.loadLibrary(System.java:1076)
    net.gotev.sipservice.SipService.loadNativeLibraries(SipService.java:1553)
    net.gotev.sipservice.SipService.access$100(SipService.java:80)
    net.gotev.sipservice.SipService$1.run(SipService.java:130)
    android.os.Handler.handleCallback(Handler.java:815)
    android.os.Handler.dispatchMessage(Handler.java:104)
    android.os.Looper.loop(Looper.java:207)
    android.app.ActivityThread.main(ActivityThread.java:5728)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
2024-03-18 13:14:20.300 6907-7033/com.unionbroad.app E/NativeCrypto: ssl=0x7f95c70800 cert_verify_callback x509_store_ctx=0x7f77ef6390 arg=0x0
2024-03-18 13:14:20.300 6907-7033/com.unionbroad.app E/NativeCrypto: ssl=0x7f95c70800 cert_verify_callback calling verifyCertificateChain authMethod=ECDHE_RSA
2024-03-18 13:14:20.341 6907-7087/com.unionbroad.app E/NativeCrypto: ssl=0x7f77c57b80 cert_verify_callback x509_store_ctx=0x7f74b3e4f0 arg=0x0
2024-03-18 13:14:20.341 6907-7087/com.unionbroad.app E/NativeCrypto: ssl=0x7f77c57b80 cert_verify_callback calling verifyCertificateChain authMethod=ECDHE_RSA
```

**Comment by nanangizz** [comment]
`freeifaddrs` seems to be introduced in [API level 24](https://android.googlesource.com/platform/bionic/+/master/docs/status.md), while Android 6 seems to use API level 23.

Note that by default the `configure-android` will use the latest API level supported by the NDK. So try to specify the API level via `APP_PLATFORM` environment variables, e.g: `APP_PLATFORM=android-23 ./configure-android`. See [here](https://developer.android.com/ndk/guides/application_mk#app_platform) for more info.

**Comment by chenmingdu** [comment]
> `freeifaddrs`似乎是在[API level 24](https://android.googlesource.com/platform/bionic/+/master/docs/status.md)中引入的，而 Android 6 似乎使用 API level 23。
> 
> 请注意，默认情况下`configure-android`将使用 NDK 支持的最新 API 级别。`APP_PLATFORM`因此尝试通过环境变量指定API级别，例如： `APP_PLATFORM=android-23 ./configure-android`。请参阅[此处](https://developer.android.com/ndk/guides/application_mk#app_platform)了解更多信息。
Thank you for your reply, I will try
