### ISSUE TITLE
Cann't install using pip

### ISSUE THREAD

**Issue by mohamad-hasan-sohan-ajini** [pjsip/pjproject#3895]
### Describe the bug

Installing from pypi comes with the error that already pasted in `log` section.

### Steps to reproduce

pip install pjsua2==2.12

### PJSIP version

2.12

### Context

Ubuntu 22.04
python3.11

### Log, call stack, etc

```shell
(venv) aj@aj-G5:~/Downloads/pjproject-2.14.1$ pip install pjsua2==2.12
Collecting pjsua2==2.12
  Using cached pjsua2-2.12.tar.gz (329 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-h2g5__km/pjsua2_7c0e086d07564861b21364e6d77c0256/setup.py", line 33, in <module>
          f = open('../../../../version.mak', 'r')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [Errno 2] No such file or directory: '../../../../version.mak'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by nanangizz** [comment]
I am afraid actually we are not the maintainer of the Python package, please contact the maintainer :)
