### ISSUE TITLE
Building python swig module fails due to either bad version written in version.mak or a bug in setup.py 

### ISSUE THREAD

**Issue by frisky5** [pjsip/pjproject#3969]
### Describe the bug

upon cloning, and building with opus, and then trying to build python swig module i got this error

> Traceback (most recent call last):
>   File "/root/pjproject/pjsip-apps/src/swig/python/setup.py", line 106, in <module>
>     setup(name="pjsua2", 
>   File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/core.py", line 146, in setup
>     _setup_distribution = dist = klass(attrs)
>   File "/usr/local/lib/python3.10/dist-packages/setuptools/dist.py", line 318, in __init__
>     self.metadata.version = self._normalize_version(self.metadata.version)
>   File "/usr/local/lib/python3.10/dist-packages/setuptools/dist.py", line 354, in _normalize_version
>     normalized = str(Version(version))
>   File "/usr/local/lib/python3.10/dist-packages/setuptools/_vendor/packaging/version.py", line 200, in __init__
>     raise InvalidVersion(f"Invalid version: '{version}'")
> setuptools.extern.packaging.version.InvalidVersion: Invalid version: '2.14--dev'
> make: *** [Makefile:42: _pjsua2.so] Error 1

so i modified the setup.py file that runs in the make process at line 59 to remove the concatenation of '-', then the building of swig worked

```
if pj_version_suffix:
     #pj_version += "-" + pj_version_suffix
     pj_version += pj_version_suffix 
```

not sure if the bug is in the setup.py or the version.mak file, but the version.mak file mentions to never be modified manually

### Steps to reproduce

1. clone master
2. build pjsip
3. build python swig module

### PJSIP version

2.14

### Context

building inside an ubuntu 20 container.

### Log, call stack, etc

```shell
N/A
```

**Comment by HayashiNiizuki** [comment]
i got this error when build python swig module 

```
/home/max/miniconda3/envs/pjsua2/compiler_compat/ld: /mnt/d/Coding/Application/pjproject-2.14.1/pjsip/lib/libpjsua2-x86_64-unknown-linux-gnu.a(media.o): warning: relocation against `_ZN2pj16AudioMediaPlayer6eof_cbEP12pjmedia_portPv' in read-only section `.text'
/home/max/miniconda3/envs/pjsua2/compiler_compat/ld: /mnt/d/Coding/Application/pjproject-2.14.1/pjsip/lib/libpjsua2-x86_64-unknown-linux-gnu.a(account.o): relocation R_X86_64_PC32 against symbol `_ZTVN2pj7AccountE' can not be used when making a shared object; recompile with -fPIC
/home/max/miniconda3/envs/pjsua2/compiler_compat/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
error: command '/usr/bin/g++' failed with exit code 1
```

**Comment by semirke** [comment]
> i got this error when build python swig module
> 
> ```
> /home/max/miniconda3/envs/pjsua2/compiler_compat/ld: /mnt/d/Coding/Application/pjproject-2.14.1/pjsip/lib/libpjsua2-x86_64-unknown-linux-gnu.a(media.o): warning: relocation against `_ZN2pj16AudioMediaPlayer6eof_cbEP12pjmedia_portPv' in read-only section `.text'
> /home/max/miniconda3/envs/pjsua2/compiler_compat/ld: /mnt/d/Coding/Application/pjproject-2.14.1/pjsip/lib/libpjsua2-x86_64-unknown-linux-gnu.a(account.o): relocation R_X86_64_PC32 against symbol `_ZTVN2pj7AccountE' can not be used when making a shared object; recompile with -fPIC
> /home/max/miniconda3/envs/pjsua2/compiler_compat/ld: final link failed: bad value
> collect2: error: ld returned 1 exit status
> error: command '/usr/bin/g++' failed with exit code 1
> ```

Hi,
sorry for reviving this thread, but I still experience the same issue on Ubuntu 22.04 and on the current main branch:
```
pjproject/pjsip-apps/src/swig/python$ make
swig -I../../../../pjlib/include -I../../../../pjlib-util/include -I../../../../pjmedia/include -I../../../../pjsip/include -I../../../../pjnath/include -c++  -w312 -threads -doxygen -python -o pjsua2_wrap.cpp ../pjsua2.i
python3 setup.py build 
/home/semirke/miniconda3/envs/whisperx/lib/python3.10/site-packages/setuptools/dist.py:289: InformationOnly: Normalizing '2.15-dev' to '2.15.dev0'
  self.metadata.version = self._normalize_version(self.metadata.version)
running build
running build_py
creating build
creating build/lib.linux-x86_64-cpython-310
copying pjsua2.py -> build/lib.linux-x86_64-cpython-310
running build_ext
building '_pjsua2' extension
creating build/temp.linux-x86_64-cpython-310
gcc -pthread -B /home/semirke/miniconda3/envs/whisperx/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/semirke/miniconda3/envs/whisperx/include -fPIC -O2 -isystem /home/semirke/miniconda3/envs/whisperx/include -fPIC -I/home/semirke/miniconda3/envs/whisperx/include/python3.10 -c pjsua2_wrap.cpp -o build/temp.linux-x86_64-cpython-310/pjsua2_wrap.o -g -O2 -DPJ_AUTOCONF=1 -O2 -DPJ_IS_BIG_ENDIAN=0 -DPJ_IS_LITTLE_ENDIAN=1 -DPJMEDIA_USE_OLD_FFMPEG=1 -DPJMEDIA_USE_OLD_FFMPEG=1 -I/home/semirke/agent/pjproject/pjlib/include -I/home/semirke/agent/pjproject/pjlib-util/include -I/home/semirke/agent/pjproject/pjnath/include -I/home/semirke/agent/pjproject/pjmedia/include -I/home/semirke/agent/pjproject/pjsip/include
g++ -pthread -B /home/semirke/miniconda3/envs/whisperx/compiler_compat -shared -Wl,-rpath,/home/semirke/miniconda3/envs/whisperx/lib -Wl,-rpath-link,/home/semirke/miniconda3/envs/whisperx/lib -L/home/semirke/miniconda3/envs/whisperx/lib -Wl,-rpath,/home/semirke/miniconda3/envs/whisperx/lib -Wl,-rpath-link,/home/semirke/miniconda3/envs/whisperx/lib -L/home/semirke/miniconda3/envs/whisperx/lib build/temp.linux-x86_64-cpython-310/pjsua2_wrap.o -lpjsua2-x86_64-pc-linux-gnu -lstdc++ -lpjsua-x86_64-pc-linux-gnu -lpjsip-ua-x86_64-pc-linux-gnu -lpjsip-simple-x86_64-pc-linux-gnu -lpjsip-x86_64-pc-linux-gnu -lpjmedia-codec-x86_64-pc-linux-gnu -lpjmedia-videodev-x86_64-pc-linux-gnu -lpjmedia-audiodev-x86_64-pc-linux-gnu -lpjmedia-x86_64-pc-linux-gnu -lpjnath-x86_64-pc-linux-gnu -lpjlib-util-x86_64-pc-linux-gnu -lsrtp-x86_64-pc-linux-gnu -lresample-x86_64-pc-linux-gnu -lgsmcodec-x86_64-pc-linux-gnu -lspeex-x86_64-pc-linux-gnu -lilbccodec-x86_64-pc-linux-gnu -lg7221codec-x86_64-pc-linux-gnu -lyuv-x86_64-pc-linux-gnu -lwebrtc-x86_64-pc-linux-gnu -lpj-x86_64-pc-linux-gnu -lssl -lcrypto -lm -lrt -lpthread -lasound -o build/lib.linux-x86_64-cpython-310/_pjsua2.cpython-310-x86_64-linux-gnu.so -L/home/semirke/agent/pjproject/pjlib/lib -L/home/semirke/agent/pjproject/pjlib-util/lib -L/home/semirke/agent/pjproject/pjnath/lib -L/home/semirke/agent/pjproject/pjmedia/lib -L/home/semirke/agent/pjproject/pjsip/lib -L/home/semirke/agent/pjproject/third_party/lib
**/home/semirke/miniconda3/envs/whisperx/compiler_compat/ld: /home/semirke/agent/pjproject/pjsip/lib/libpjsua2-x86_64-pc-linux-gnu.a(media.o): warning: relocation against `_ZN2pj16AudioMediaPlayer6eof_cbEP12pjmedia_portPv' in read-only section `.text'
/home/semirke/miniconda3/envs/whisperx/compiler_compat/ld: /home/semirke/agent/pjproject/pjsip/lib/libpjsua2-x86_64-pc-linux-gnu.a(account.o): relocation R_X86_64_PC32 against symbol `_ZTVN2pj7AccountE' can not be used when making a shared object; recompile with -fPIC**
/home/semirke/miniconda3/envs/whisperx/compiler_compat/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
error: command '/usr/bin/g++' failed with exit code 1
make: *** [Makefile:43: _pjsua2.so] Error 1

```

Am I making something wrong?
Thanks!
