### ISSUE TITLE
pip install pjsua2 is not possible. pjsip-apps/src/python/ is deprecated. Must use pjsip-apps/src/swig/python (SOLVED)

### ISSUE THREAD

**Issue by blackhold** [pjsip/pjproject#4126]
### Describe the bug

I'm trying to build pjsua2 with pip

`pip3 install pjsua2`

[https://pypi.org/project/pjsua2/](https://pypi.org/project/pjsua2/)

I see I have to install pjproject, so I installed it using git clone and all ok. But when I go to compile it for python in pjsip-apps/src/python I found first that setup.py file have mixes of tabs and spaces, I have fixed but when I run make it gives an error.

### Steps to reproduce

as root

```
# cd /home/laura/dev/test_callcenter/
# git clone https://github.com/pjsip/pjproject.git
# cd pjproject
# ./configure --enable-shared --with-python=python3; make dep; make; make install
# ldconfig
# cd pjsip-apps/src/python
# python3 setup.py build
  File "/home/laura/dev/test_callcenter/pjproject-2.14.1/pjsip-apps/src/python/setup.py", line 35
    if len(tokens)>1:
TabError: inconsistent use of tabs and spaces in indentation
# make
python setup.py build
  File "/home/laura/dev/test_callcenter/pjproject/pjsip-apps/src/python/setup.py", line 35
    if len(tokens)>1:
TabError: inconsistent use of tabs and spaces in indentation
make: *** [Makefile:2: all] Error 1

# apt install python3-autopep8

# autopep8 -i setup.py

# make
python setup.py build
  File "/home/laura/dev/test_callcenter/pjproject/pjsip-apps/src/python/setup.py", line 52
    print 'Unable to get PJ_VERSION_MAJOR'
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
make: *** [Makefile:2: all] Error 1

# vi setup.py +52

# export
[...]
declare -x OLDPWD="/home/laura/dev/test_callcenter/pjproject"
declare -x PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
declare -x PJ_VERSION_MAJOR="2"
declare -x PJ_VERSION_MINOR="14"
declare -x PJ_VERSION_REV="1"
declare -x PWD="/home/laura/dev/test_callcenter/pjproject/pjsip-apps/src/python"
declare -x SHELL="/bin/bash"
declare -x SHLVL="1"
declare -x TERM="xterm-256color"
declare -x USER="root"
declare -x XDG_DATA_DIRS="/root/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share")
```

I have fixed versions in setup.py file and then make again

```
# make
python setup.py build
/home/laura/dev/test_callcenter/pjproject/pjsip-apps/src/python/setup.py:20: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.core import setup, Extension
running build
running build_py
creating build
creating build/lib.linux-x86_64-3.11
copying pjsua.py -> build/lib.linux-x86_64-3.11
running build_ext
building '_pjsua' extension
creating build/temp.linux-x86_64-3.11
[...]
_pjsua.h:76:9: error: ‘PyObj_pjsip_cred_info’ has no member named ‘ob_type’
   76 |     self->ob_type->tp_free((PyObject*)self);
      |         ^~
[...]
_pjsua.h: In function ‘PyObj_pjsua_callback_delete’:
_pjsua.h:262:9: error: ‘PyObj_pjsua_callback’ has no member named ‘ob_type’
  262 |     self->ob_type->tp_free((PyObject*)self);
      |         ^~
_pjsua.h: At top level:
[...]
_pjsua.h: In function ‘PyObj_pjsua_media_config_delete’:
_pjsua.h:676:9: error: ‘PyObj_pjsua_media_config’ has no member named ‘ob_type’
  676 |     self->ob_type->tp_free((PyObject*)self);
      |         ^~
[...]
_pjsua.h: In function ‘PyObj_pjsua_config_delete’:
_pjsua.h:837:9: error: ‘PyObj_pjsua_config’ has no member named ‘ob_type’
  837 |     self->ob_type->tp_free((PyObject*)self);
      |         ^~
[...]
_pjsua.h: In function ‘PyObj_pjsua_logging_config_delete’:
_pjsua.h:1048:9: error: ‘PyObj_pjsua_logging_config’ has no member named ‘ob_type’
 1048 |     self->ob_type->tp_free((PyObject*)self);
      |         ^~
[...]
_pjsua.h: In function ‘PyObj_pjsua_msg_data_delete’:
_pjsua.h:1214:9: error: ‘PyObj_pjsua_msg_data’ has no member named ‘ob_type’
 1214 |     self->ob_type->tp_free((PyObject*)self);
      |         ^~
[...]
_pjsua.h: In function ‘PyObj_pjsua_transport_config_delete’:
_pjsua.h:1346:11: error: ‘PyObj_pjsua_transport_config’ has no member named ‘ob_type’; did you mean ‘qos_type’?
 1346 |     self->ob_type->tp_free((PyObject*)self);
      |           ^~~~~~~
      |           qos_type
[...]
_pjsua.h: In function ‘PyObj_pjsua_transport_info_delete’:
_pjsua.h:1571:9: error: ‘PyObj_pjsua_transport_info’ has no member named ‘ob_type’
 1571 |     self->ob_type->tp_free((PyObject*)self);
      |         ^~
[...]
_pjsua.h: In function ‘PyObj_pjsua_acc_config_delete’:
_pjsua.h:1766:9: error: ‘PyObj_pjsua_acc_config’ has no member named ‘ob_type’
 1766 |     self->ob_type->tp_free((PyObject*)self);
      |         ^~
[...]
_pjsua.h: In function ‘PyObj_pjsua_acc_info_delete’:
_pjsua.h:2171:9: error: ‘PyObj_pjsua_acc_info’ has no member named ‘ob_type’
 2171 |     self->ob_type->tp_free((PyObject*)self);
      |         ^~
[...]
more than these errors
[...]
_pjsua.c: In function ‘DL_EXPORT’:
_pjsua.c:4430:1: error: expected declaration specifiers before ‘init_pjsua’
 4430 | init_pjsua(void)
      | ^~~~~~~~~~
_pjsua.c:4612: error: expected ‘{’ at end of input
_pjsua.c:4612: warning: control reaches end of non-void function [-Wreturn-type]
_pjsua.c: At top level:
_pjsua.c:3997:20: warning: ‘py_pjsua_methods’ defined but not used [-Wunused-variable]
 3997 | static PyMethodDef py_pjsua_methods[] =
      |                    ^~~~~~~~~~~~~~~~
error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
make: *** [Makefile:2: all] Error 1
```

Due is c I don't know how to continue :(

Also if I try to run again pip it shows:

```
(venv) laura@triptofan:~/dev/test_callcenter$ pip3 install pjsua2
Collecting pjsua2
  Using cached pjsua2-2.12.tar.gz (329 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-4kwezv0a/pjsua2_9cd1d7f4f4ad418dacfdefe37f23ef90/setup.py", line 33, in <module>
          f = open('../../../../version.mak', 'r')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [Errno 2] No such file or directory: '../../../../version.mak'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

If I place file version.mak to / then the message error is:

```
$ pip3 install pjsua2
Collecting pjsua2
  Using cached pjsua2-2.12.tar.gz (329 kB)
  Preparing metadata (setup.py) ... done
Discarding https://files.pythonhosted.org/packages/7c/a4/2a60051d51d163f366379d0877621a1798a8d842d91f5b696072c902502b/pjsua2-2.12.tar.gz (from https://pypi.org/simple/pjsua2/): Requested pjsua2 from https://files.pythonhosted.org/packages/7c/a4/2a60051d51d163f366379d0877621a1798a8d842d91f5b696072c902502b/pjsua2-2.12.tar.gz has inconsistent version: expected '2.12', but metadata has '2.14.1'
ERROR: Could not find a version that satisfies the requirement pjsua2 (from versions: 2.12)
ERROR: No matching distribution found for pjsua2

```
I tried to install pjsua2-2.12 and also I have the same problem, build works, but no pip install pjsua2 when I place file version.mak to /

I see the option to install libpjproject-dev but is not available in debian, only in old ubuntu versions.

### PJSIP version

2.14.? git one (also tested in 2.14.1 and 2.12)

### Context

Debian 12 bookworm

Python 3.11

### Log, call stack, etc

```shell
error shown in "steps to reproduce"
```

**Comment by blackhold** [comment]
Well, I have looked in closed tickets and **I see that the only option is to install using swig**

[https://docs.pjsip.org/en/latest/pjsua2/building.html#building-python-swig-module](https://docs.pjsip.org/en/latest/pjsua2/building.html#building-python-swig-module)

```
# cd pjsip-apps/src/swig/python
# make
# make install
```

I have installed the program as root but I would like to make the modules available to my application. I tried to compile las three lines as user but when importing pjsua2 with python, it don't founds the library.

This hello world as root works for me as root, but not from my user

[https://docs.pjsip.org/en/latest/pjsua2/hello_world.html#python3](https://docs.pjsip.org/en/latest/pjsua2/hello_world.html#python3)

```
import pjsua2 as pj

# Subclass to extend the Account and get notifications etc.
class Account(pj.Account):
  def onRegState(self, prm):
      print("***OnRegState: " + prm.reason)

# pjsua2 test function
def pjsua2_test():
  # Create and initialize the library
  ep_cfg = pj.EpConfig()
  ep = pj.Endpoint()
  ep.libCreate()
  ep.libInit(ep_cfg)

  # Create SIP transport. Error handling sample is shown
  sipTpConfig = pj.TransportConfig();
  sipTpConfig.port = 5060;
  ep.transportCreate(pj.PJSIP_TRANSPORT_UDP, sipTpConfig);
  # Start the library
  ep.libStart();

  acfg = pj.AccountConfig();
  acfg.idUri = "sip:test@sip.pjsip.org";
  acfg.regConfig.registrarUri = "sip:sip.pjsip.org";
  cred = pj.AuthCredInfo("digest", "*", "test", 0, "pwtest");
  acfg.sipConfig.authCreds.append( cred );
  # Create the account
  acc = Account();
  acc.create(acfg);
  # Here we don't have anything else to do..
  time.sleep(10);

  # Destroy the library
  ep.libDestroy()

#
# main()
#
if __name__ == "__main__":
  pjsua2_test()
```

Which files y have to place to my venv/lib/python3.11/site-packages/ to get it work?

Thanks you much

**Comment by blackhold** [comment]
Well! finally I have solved! :) sorry for the noise and spect it will be useful for those that have the same problem :)

Once I have it working as root, I placed in /root/.local//lib/python3.11/site-packages/ and found the files there:

```
root@triptofan:~/.local/lib/python3.11/site-packages# ls
pjsua2-2.14_dev.egg-info  _pjsua2.cpython-311-x86_64-linux-gnu.so  pjsua2.py  __pycache__
```

Simply I copied them to my virtualenv folder and gave right permissions:

```
root@triptofan:~/.local/lib/python3.11/site-packages# cp * /home/laura/dev/test_callcenter/venv/lib/python3.11/site-packages/pjsua2/
cp: no s’ha especificat «-r»; es descarta el directori '__pycache__'

root@triptofan:~/.local/lib/python3.11/site-packages# cd /home/laura/dev/test_callcenter/venv/lib/python3.11/site-packages/pjsua2

root@triptofan:/home/laura/dev/test_callcenter/venv/lib/python3.11/site-packages/pjsua2# chown -R laura:laura *
```

Due I have saved them in pjsua2 folder, I have to modify hello world script 

```
(venv) laura@triptofan:~/dev/test_callcenter$ vi pjsua2_hello_world.py
# import pjsua2 as pj   # old line
from pjsua2 import pjsua2 as pj  # new line
```

And hello world script is working :)

**Comment by blackhold** [comment]
I close ticket, due I found a solution.

**Comment by landikurd** [comment]
How i can contact to you?

**Comment by blackhold** [comment]
> How i can contact to you?

Send me a message through form contact of https://capa8.net mention you contact me from pjsua2 forum.
